---
title: "Veganishism"
date: 2017-12-26T17:23:36+13:00
draft: true
---

I am a meat-loving part-time vegan. Since November 1st I have been dodging meat, dairy and eggs from Monday to Friday. 

Initially I just want to slash my cholesterol levels down from 6.4 to sub-5.0. Eventually I'd like to try being a full-time vegan, but I want to make it work for me, and I want to go easy on myself.

What? Veganism is so extreme, right? Well, sure, it can be.

* Why veganish?

What led me here? A few things ...

** The Cholesterol factor

  Cholesterol is a type of fat circulating in your blood. If you have too much you can get into real trouble. I don't know if it's technically hereditary, but it's been a problem in my family for generations.

  I have a cholesterol level of 6.4. Ideally you should be about 4.0, but recommendations suggest below 5.0 is good.

*** How to reduce cholesterol.
  + Drink less, stop smoking.
  + Get plenty of light exercise. One hour of walking each day beats a weekly gym visit.
  + Reduce high-cholesterol foods
  + Maybe medicate (statins)
 
*** Initial attmepts
  + I did the first two. It didn't help. 
  + I did lots more exercise. No joy. 
  + Tried reducing my high-cholesterol foods here and there. Nada. 
  + I have considered statins, but I've been warned off them by the experiences of family members

  2 years later ... looking at every list of high-cholesterol foods, it hit me square in the face:

  * High-cholesterol foods almost exclusively include meat (inc fish), dairy, eggs.
  * The only vegan-friendly exceptions I keep seeing are margarine and coconut milk.

** The environment

 Meat and dairy
